version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: fullstack_training
    ports: ["5432:5432"]
    volumes: [ "db_data:/var/lib/postgresql/data" ]
  adminer:
    image: adminer
    ports: ["8080:8080"]

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - db

  web:
    build:
      context: ./frontend
    environment:
      RUST_API_BASE: http://backend:3001
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
      JWT_COOKIE_NAME: ggf_session
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 10s
      timeout: 2s
      retries: 10

      
volumes:
  db_data:
